name: reggie_take_out

services:
  reggie_mysql:
    image: reggie_mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reggie
    restart: always
    networks:
      - network01

  reggie_spring:
    image: reggie_take_out:1.0-SNAPSHOT
    ports:
      - "8080:8080"


    restart: always
    networks:
      - network01
    depends_on:
      - reggie_mysql

networks:
  network01: